---
title: "simple-pb"
author: "Yi"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(kableExtra)
library(meta)
library(cubature)
library(metasens)
library(ggplot2)
library(dplyr)
library(MCMCpack)
```

# Example 1

## NN model without PB

```{r}
data2 <- read.csv("niel-weise21-cc.csv")

m1 <- metaprop(y1, n1, data = data2, sm = "PLOGIT")
# yi <- m1$TE
# vi <- m1$seTE
yi <- log(data2$y1cc/data2$c1cc)
vi <- 1/data2$y1cc + 1/data2$c1cc
## Find initial values
llk.NN1 = function(par) {
  mu = par[1]
  tau2 = par[2]
  
  llk <- dnorm(yi, mean = mu, sd = sqrt(vi + tau2), log = T)
  
  l3 = sum(llk, na.rm = TRUE)
  
  return(-l3)
}

start = c(-1, 0.1)
result = try(nlminb(start, llk.NN1,
                    lower = c(-Inf, 0),
                    upper = c(Inf, Inf)), silent = TRUE)

hes <- numDeriv::hessian(llk.NN1, result$par)
var.matrix <- solve(hes)
mu01.se <- sqrt(var.matrix[1,1])
mu01.lb <- result$par[1] + qnorm((1-0.95)/2, lower.tail = TRUE)*mu01.se
mu01.ub <- result$par[1] + qnorm((1-0.95)/2, lower.tail = FALSE)*mu01.se

```

## BN model without PB

```{r}
data <- read.csv("niel-weise21.csv")

yi <- data$y1
ni <- data$n1

## Find initial values
llk.BN1 = function(par) {
  mu = par[1]
  tau2 = par[2]
  
  f <- function(theta) dbinom(yi, ni, prob = plogis(theta)) * dnorm(theta, mean = mu, sd = sqrt(tau2))
  
  prob.prior <- hcubature(f, lowerLimit = -Inf, upperLimit = Inf, fDim = length(yi))$integral
  
  l3 = sum(log(prob.prior), na.rm = TRUE)
  
  return(-l3)
}

start = c(-1, 0.1)
result = try(nlminb(start, llk.BN1,
                    lower = c(-Inf, 0),
                    upper = c(Inf, Inf)), silent = TRUE)

hes <- numDeriv::hessian(llk.BN1, result$par)
var.matrix <- solve(hes)
mu1.se <- sqrt(var.matrix[1,1])
mu1.lb <- result$par[1] + qnorm((1-0.95)/2, lower.tail = TRUE)*mu1.se
mu1.ub <- result$par[1] + qnorm((1-0.95)/2, lower.tail = FALSE)*mu1.se

inival1 <- result$par

```

## The number of unpubished

```{r}

rho_vec <- round(seq(-0.9, 0.9, 0.3), 2)
prob_min <- seq(0.1,0.9,0.1)

M <- NULL
for(sa.rho in rho_vec) {
  
  for(sa.pmin in prob_min){
    
    
    rho <- sa.rho
    P_max <- 0.99
    P_min <- sa.pmin
    
    n_min <- min(ni) 
    n_max <- max(ni)
    
    a1 <- (qnorm(P_max)-qnorm(P_min))/(sqrt(n_max)-sqrt(n_min))
    a0 <- qnorm(P_max)-a1*sqrt(n_max)
    M <- c(M, sum((1 - pnorm(a0+a1*sqrt(ni)))/pnorm(a0+a1*sqrt(ni))) )
    
  }
}

round(M)

a1 <- NULL
for(sa.rho in rho_vec) {
  
  for(sa.pmin in prob_min){
    
    
    rho <- sa.rho
    P_max <- 0.99
    P_min <- sa.pmin
    
    n_min <- min(ni) 
    n_max <- max(ni)
    
    a1 <- c(a1, (qnorm(P_max)-qnorm(P_min))/(sqrt(n_max)-sqrt(n_min)))
    
  }
}

a1

a0 <- NULL
for(sa.rho in rho_vec) {
  
  for(sa.pmin in prob_min){
    
    
    rho <- sa.rho
    P_max <- 0.99
    P_min <- sa.pmin
    
    n_min <- min(ni) 
    n_max <- max(ni)
    
    a1 <- (qnorm(P_max)-qnorm(P_min))/(sqrt(n_max)-sqrt(n_min))
    a0 <- c(a0, qnorm(P_max)-a1*sqrt(n_max))
    
  }
}

a0

```

## BN model with PB

```{r}
par1 <- NULL
for(sa.rho in rho_vec) {
  
  for(sa.pmin in prob_min){
    
    # rho <- 0
    # P_min <- 0.2
    # 
    rho <- sa.rho
    P_max <- 0.99
    P_min <- sa.pmin
    
    llk.BN1sa = function(par) {
      mu = par[1]
      tau2 = par[2]
      tau <- sqrt(tau2)
      
      f <- function(theta) {
        
        n_min <- min(ni) 
        n_max <- max(ni)
        
        a1 <- (qnorm(P_max)-qnorm(P_min))/(sqrt(n_max)-sqrt(n_min))
        a0 <- qnorm(P_max)-a1*sqrt(n_max)
        
        pnorm((a0+a1*sqrt(ni)+rho*(theta-mu)/tau)/sqrt(1-rho^2))/pnorm(a0+a1*sqrt(ni)) * 
          dbinom(yi, ni, prob = plogis(theta)) * 
          dnorm(theta, mean = mu, sd = sqrt(tau2))
    
        
      }
      
      prob.prior = cubature::hcubature(f, lowerLimit = -Inf, upperLimit = Inf, fDim = length(yi), tol = 1e-10)$integral
      
      l3 = sum(log(prob.prior), na.rm = TRUE)
      
      return(-l3)
    }
    
    result = nlminb(inival1, llk.BN1sa,
                    lower = c(-Inf, 0), upper = c(Inf, 5))
    
    hes <- numDeriv::hessian(llk.BN1sa, result$par)
    var.matrix <- solve(hes)
    u1.se <- sqrt(var.matrix[1,1])
    u1.lb <- result$par[1] + qnorm((1-0.95)/2, lower.tail = TRUE)*u1.se
    u1.ub <- result$par[1] + qnorm((1-0.95)/2, lower.tail = FALSE)*u1.se
    
    par1 <- rbind(par1, c(result$par, u1.lb, u1.ub, result$convergence))
    
  }
}
```

## Exapme 1 Table

```{r}
result1 <- cbind.data.frame(
  M = M,
  rho = rep(rho_vec, each=length(prob_min)), 
  prob = sprintf("(%.2f, %.2f)", prob_min, rep(0.99, length(prob_min))),
  mu = round(par1[,1],3),
  CI = sprintf("(%.2f, %.2f)", par1[,3], par1[,4]),
  tau = round(par1[,2],3),
  OR = round(exp(par1[,1]),3),
  cov = par1[,5])

kableExtra::kbl(result1)%>%kable_styling("striped", position = "right")

df1 <- cbind.data.frame(
  rho = rep(rho_vec, each=length(prob_min)), 
  minprob = rep(seq(0.1,0.9,0.1), length(rho_vec)),
  mu = round(par1[,1],3),
  mulb = round(par1[,3],3),
  muub = round(par1[,4],3),
  OR = round(exp(par1[,1]),3),
  tau = round(par1[,2],3)
  )

m1 <- metaprop(y1, n1, data = data, sm = "PLOGIT")
cop1a <- copas(m1, rho.bound = 0.9)
cop1b <- copas(m1, rho.bound = 0.6)
cop1c <- copas(m1, rho.bound = 0.3)
```

## Exapme 1 Figure

```{r, fig.height=12, fig.width=8}
par(mfrow = c(2,3))
## rho = -0.9
df0 <- c(NA, 1, inival1[1], mu1.lb, mu1.ub,inival1[2], exp(inival1[1]))
df11 <- rbind(df1[df1$rho==-0.9, ], df0)
plot(df11$minprob, df11$mu, type = "b", 
     ylim = c(-6, 0), xlim = rev(c(0.1,1)),
     xlab = "Probability of publishing study with smallest subjects",
     ylab = "Effect Size (lnOR)")
lines(df11$minprob, df11$mulb)
lines(df11$minprob, df11$muub)
abline(h=0)
title(main = "A. Proposal (rho = -0.9)")

## rho = -0.6
df11 <- rbind(df1[df1$rho==-0.6, ], df0)
plot(df11$minprob, df11$mu, type = "b", 
     ylim = c(-6, 0), xlim = rev(c(0.1,1)),
     xlab = "Probability of publishing study with smallest subjects",
     ylab = "Effect Size (lnOR)")
lines(df11$minprob, df11$mulb)
lines(df11$minprob, df11$muub)
abline(h=0)
title(main = "B. Proposal (rho = -0.6)")

## rho = -0.3
df11 <- rbind(df1[df1$rho==-0.3, ], df0)
plot(df11$minprob, df11$mu, type = "b", 
     ylim = c(-6, 0), xlim = rev(c(0.1,1)),
     xlab = "Probability of publishing study with smallest subjects",
     ylab = "Effect Size (lnOR)")
lines(df11$minprob, df11$mulb)
lines(df11$minprob, df11$muub)
abline(h=0)
title(main = "C. Proposal (rho = -0.3)")


copdf <- data.frame(
  minprob = cop1a$publprob,
  mu = cop1a$TE.slope, 
  mulb = cop1a$lower.slope,
  muub = cop1a$upper.slope)
plot(copdf$minprob, copdf$mu, type = "b", 
     ylim = c(-6, 0), xlim = rev(c(0.1,1)),
     xlab = "Probability of publishing study with largest SE",
     ylab = "Effect Size (lnOR)")
lines(copdf$minprob, copdf$mulb)
lines(copdf$minprob, copdf$muub)
abline(h=0)
title(main = "D. Copas selection model (rho = 0.9)")

copdf <- data.frame(
  minprob = cop1b$publprob,
  mu = cop1b$TE.slope, 
  mulb = cop1b$lower.slope,
  muub = cop1b$upper.slope)
plot(copdf$minprob, copdf$mu, type = "b", 
     ylim = c(-6, 0), xlim = rev(c(0.1,1)),
     xlab = "Probability of publishing study with largest SE",
     ylab = "Effect Size (lnOR)")
lines(copdf$minprob, copdf$mulb)
lines(copdf$minprob, copdf$muub)
abline(h=0)
title(main = "E. Copas selection model (rho = 0.6)")

copdf <- data.frame(
  minprob = cop1c$publprob,
  mu = cop1c$TE.slope, 
  mulb = cop1c$lower.slope,
  muub = cop1c$upper.slope)
plot(copdf$minprob, copdf$mu, type = "b", 
     ylim = c(-6, 0), xlim = rev(c(0.1,1)),
     xlab = "Probability of publishing study with largest SE",
     ylab = "Effect Size (lnOR)")
lines(copdf$minprob, copdf$mulb)
lines(copdf$minprob, copdf$muub)
abline(h=0)
title(main = "F. Copas selection model (rho = 0.3)")
par(mfrow = c(1,1))
```



# Example 2
## NN model without PB

```{r}
data2 <- read.csv("niel-weise21-cc.csv")

m1 <- metaprop(y1, n1, data = data2, sm = "PLOGIT")
# yi <- m1$TE
# vi <- m1$seTE
yi <- log((data2$y1cc/data2$c1cc)/(data2$y0cc/data2$c0cc))
vi <- 1/data2$y1cc + 1/data2$c1cc
## Find initial values
llk.NN1 = function(par) {
  mu = par[1]
  tau2 = par[2]
  
  llk <- dnorm(yi, mean = mu, sd = sqrt(vi + tau2), log = T)
  
  l3 = sum(llk, na.rm = TRUE)
  
  return(-l3)
}

start = c(-1, 0.1)
result = try(nlminb(start, llk.NN1,
                    lower = c(-Inf, 0),
                    upper = c(Inf, Inf)), silent = TRUE)

hes <- numDeriv::hessian(llk.NN1, result$par)
var.matrix <- solve(hes)
mu01.se <- sqrt(var.matrix[1,1])
mu01.lb <- result$par[1] + qnorm((1-0.95)/2, lower.tail = TRUE)*mu01.se
mu01.ub <- result$par[1] + qnorm((1-0.95)/2, lower.tail = FALSE)*mu01.se

```


## BN model without PB

```{r}
data <- read.csv("niel-weise21.csv")

y1 <- data$y1
yi <- data$y1+data$y0
n1 <- data$n1
n0 <- data$n0
ni <- n1+n0

## Find initial values
llk.BN2 = function(par) {
  mu = par[1]
  tau2 = par[2]
  
  f <- function(theta) {
    
    dbinom(y1, yi, prob = plogis(log(n1 / n0) + theta)) * dnorm(theta, mean = mu, sd = sqrt(tau2))
    
  }
  
  prob.prior = hcubature(f, lowerLimit = -Inf, upperLimit = Inf, fDim = length(y1), tol = 1e-10)$integral
  
  l3 = sum(log(prob.prior + 1e-30), na.rm = TRUE)
  
  return(-l3)
}

start = c(-1, 0.1)
result = try(nlminb(start, llk.BN2,
                    lower = c(-Inf, 0),
                    upper = c(Inf, 5)), silent = TRUE)

hes <- numDeriv::hessian(llk.BN2, result$par)
var.matrix <- solve(hes)
mu2.se <- sqrt(var.matrix[1,1])
mu2.lb <- result$par[1] + qnorm((1-0.95)/2, lower.tail = TRUE)*mu2.se
mu2.ub <- result$par[1] + qnorm((1-0.95)/2, lower.tail = FALSE)*mu2.se

inival2 <- result$par
```

## BN model with PB

```{r}
par2 <- NULL
for(sa.rho in rho_vec) {
  
  for(sa.pmin in prob_min){
    
    rho <- sa.rho
    P_max <- 0.99
    P_min <- sa.pmin
    
    
    llk.BN2sa = function(par) {
      mu = par[1]
      tau2 = par[2]
      tau <- sqrt(tau2)
      
      f <- function(theta) {
        
        
        n_min <- min(ni) 
        n_max <- max(ni)
        
        a1 <- -(qnorm(1-P_max)-qnorm(1-P_min))/(sqrt(n_max)-sqrt(n_min))
        a0 <- -a1*sqrt(n_max)-qnorm(1-P_max)

        pnorm((a0+a1*sqrt(ni)+rho*(theta-mu)/tau)/sqrt(1-rho^2))/pnorm(a0+a1*sqrt(ni)) * 
          dbinom(y1, yi, prob = plogis(log(n1 / n0) + theta)) * 
          dnorm(theta, mean = mu, sd = tau)
        
      }
      
      prob.prior = cubature::hcubature(f, lowerLimit = -Inf, upperLimit = Inf, fDim = length(yi), tol = 1e-10)$integral
      
      l3 = sum(log(prob.prior), na.rm = TRUE)
      
      return(-l3)
    }
    
    result = try(nlminb(inival2, llk.BN2sa,
                         lower = c(-Inf, 0),
                         upper = c(Inf, 5)), silent = TRUE)
    hes <- numDeriv::hessian(llk.BN2sa, result$par)
    var.matrix <- solve(hes)
    u1.se <- sqrt(var.matrix[1,1])
    u1.lb <- result$par[1] + qnorm((1-0.95)/2, lower.tail = TRUE)*u1.se
    u1.ub <- result$par[1] + qnorm((1-0.95)/2, lower.tail = FALSE)*u1.se
    
    par2 <- rbind(par2, c(result$par, u1.lb, u1.ub, result$convergence))
    
  }
}

```


## Exapme 2 Table 1

```{r}
result2 <- cbind.data.frame(
  M = M,
  rho = rep(rho_vec, each=length(prob_min)), 
  prob = sprintf("(%.2f, %.2f)", prob_min, rep(0.99, length(prob_min))),
  mu = round(par2[,1],3),
  CI = sprintf("(%.2f, %.2f)", par2[,3], par2[,4]),
  tau = round(par2[,2],3),
  OR = round(exp(par2[,1]),3),
  cov = par2[,5])


kableExtra::kbl(result2)%>%kable_styling("striped", position = "right")

df2 <- cbind.data.frame(
  rho = rep(rho_vec, each=length(prob_min)), 
  minprob = rep(seq(0.1,0.9,0.1), length(rho_vec)),
  mu = round(par2[,1],3),
  mulb = round(par2[,3],3),
  muub = round(par2[,4],3),
  OR = round(exp(par2[,1]),3),
  tau = round(par2[,2],3)
  )

m2 <- metabin(y1, n1, y0, n0, data = data, sm = "OR")
cop2a <- copas(m2, rho.bound = 0.9)
cop2b <- copas(m2, rho.bound = 0.6)
cop2c <- copas(m2, rho.bound = 0.3)


```


## HN model without PB

```{r}
data <- read.csv("niel-weise21.csv")

y1 <- data$y1
y0 <- data$y0
yi <- y1+y0
n1 <- data$n1
n0 <- data$n0
ni <- n1+n0

## Find initial values
llk.HN2 = function(par) {
  mu = par[1]
  tau2 = par[2]
  
  jmin <- pmax(0, yi-n0)
  jmax <- pmin(yi, n1)
  
  f <- function(theta) {
    
  hyper <- NULL
  
   for(i in 1:length(yi)){
   
    hyper <- c(hyper, dnoncenhypergeom(x = y1[i], n1[i], n0[i], yi[i], exp(theta))* dnorm(theta, mean = mu, sd = sqrt(tau2)))
 # j <- jmin[i]:jmax[i]
 #    numerator <- choose(n1[i], y1[i])*choose(n0[i], y0[i])*exp(theta*y1[i])
 #    denominator <- sum(choose(n1[i], j)*choose(n0[i], yi[i]-j)*exp(theta*j), na.rm = T)
 #    hyper <- c(hyper, numerator/denominator* dnorm(theta, mean = mu, sd = sqrt(tau2)))
    }
    
    hyper

  }
  
  prob.prior = hcubature(f, lowerLimit = -10, upperLimit = 10, fDim = length(yi), tol = 1e-10)$integral
  
  l3 = sum(log(prob.prior), na.rm = TRUE)
  
  return(-l3)
}

start = c(-1.3, 0.1)
result = try(nlminb(start, llk.HN2, 
                    lower = c(-Inf, 0),
                    upper = c(Inf, 5)), silent = TRUE)

hes <- numDeriv::hessian(llk.HN2, result$par)
var.matrix <- solve(hes)
mu3.se <- sqrt(var.matrix[1,1])
mu3.lb <- result$par[1] + qnorm((1-0.95)/2, lower.tail = TRUE)*mu3.se
mu3.ub <- result$par[1] + qnorm((1-0.95)/2, lower.tail = FALSE)*mu3.se


inival3 <- result$par
```


## HN model with PB

```{r}
par3 <- NULL
for(sa.rho in rho_vec) {
  
  for(sa.pmin in prob_min){
    
    
    rho <- sa.rho
    # rho <- 0.2
    P_max <- 0.99
    # P_min <- 0.2
    P_min <- sa.pmin
    
    llk.HN2sa = function(par) {
      mu = par[1]
      tau2 = par[2]
      tau <- sqrt(tau2)
      
      # mu = 0
      # tau2 = 1
      # tau = 1
      
      n_min <- min(ni)
      n_max <- max(ni)

      a1 <- -(qnorm(1-P_max)-qnorm(1-P_min))/(sqrt(n_max)-sqrt(n_min))
      a0 <- -a1*sqrt(n_max)-qnorm(1-P_max)

      
      f <- function(theta) {
    
      hyper <- NULL
      
       for(i in 1:length(yi)){
       
        hyper <- c(hyper, pnorm((a0+a1*sqrt(ni[i])+rho*(theta-mu)/tau)/sqrt(1-rho^2))/pnorm(a0+a1*sqrt(ni[i]))*
                     dnoncenhypergeom(x = y1[i], n1[i], n0[i], yi[i], exp(theta))*
                     dnorm(theta, mean = mu, sd = sqrt(tau2)))
     
        }
        
        hyper
    
      }
  
      prob.prior = hcubature(f, lowerLimit = -10, upperLimit = 10, fDim = length(yi), tol = 1e-10)$integral
      
      l3 = sum(log(prob.prior), na.rm = TRUE)
      
      return(-l3)
    }
    
    result = try(nlminb(inival3, llk.HN2sa,
                         lower = c(-Inf, 0),
                         upper = c(Inf, 5)), silent = TRUE)
    
    hes <- numDeriv::hessian(llk.HN2sa, result$par)
    var.matrix <- solve(hes)
    u1.se <- sqrt(var.matrix[1,1])
    u1.lb <- result$par[1] + qnorm((1-0.95)/2, lower.tail = TRUE)*u1.se
    u1.ub <- result$par[1] + qnorm((1-0.95)/2, lower.tail = FALSE)*u1.se
    
    par3 <- rbind(par3, c(result$par, u1.lb, u1.ub, result$convergence))
    
  }
}

# par
```

## Exapme 2 Table


```{r}
result3 <- cbind.data.frame(
  M = M,
  rho = rep(rho_vec, each=length(prob_min)), 
  prob = sprintf("(%.2f, %.2f)", prob_min, rep(0.99, length(prob_min))),
  mu = round(par3[,1],3),
  CI = sprintf("(%.2f, %.2f)", par3[,3], par3[,4]),
  tau = round(par3[,2],3),
  OR = round(exp(par3[,1]),3),
  cov = par3[,5])


kableExtra::kbl(result3)%>%kable_styling("striped", position = "right")

df3 <- cbind.data.frame(
  rho = rep(rho_vec, each=length(prob_min)), 
  minprob = rep(seq(0.1,0.9,0.1), length(rho_vec)),
  mu = round(par3[,1],3),
  mulb = round(par3[,3],3),
  muub = round(par3[,4],3),
  OR = round(exp(par3[,1]),3),
  tau = round(par3[,2],3)
  )

```


## Exapme 2 Figure

```{r, fig.height=12, fig.width=12}
par(mfrow = c(3,3))

df20 <- c(NA, 1, inival2[1], mu2.lb, mu2.ub, inival2[2], exp(inival2[1]))
df21 <- rbind(df2[df2$rho==-0.9, ], df20)
plot(df21$minprob, df21$mu, type = "b", 
     ylim = c(-3,1), xlim = rev(c(0.1,1)),
     xlab = "Probability of publishing study with smallest subjects",
     ylab = "Effect Size (lnOR)")
lines(df21$minprob, df21$mulb)
lines(df21$minprob, df21$muub)
abline(h=0)
title(main = "A. Proposal (BN, rho = -0.9)")

## rho = -0.6
df21 <- rbind(df2[df2$rho==-0.6, ], df20)
plot(df21$minprob, df21$mu, type = "b", 
     ylim = c(-3,1), xlim = rev(c(0.1,1)),
     xlab = "Probability of publishing study with smallest subjects",
     ylab = "Effect Size (lnOR)")
lines(df21$minprob, df21$mulb)
lines(df21$minprob, df21$muub)
abline(h=0)
title(main = "B. Proposal (BN, rho = -0.6)")

## rho = -0.3
df21 <- rbind(df2[df2$rho==-0.3, ], df20)
plot(df21$minprob, df21$mu, type = "b", 
     ylim = c(-3,1), xlim = rev(c(0.1,1)),
     xlab = "Probability of publishing study with smallest subjects",
     ylab = "Effect Size (lnOR)")
lines(df21$minprob, df21$mulb)
lines(df21$minprob, df21$muub)
abline(h=0)
title(main = "C. Proposal (BN, rho = -0.3)")

## rho = -0.9
df30 <- c(NA, 1, inival3[1], mu3.lb, mu3.ub, inival3[2], exp(inival3[1]))
df31 <- rbind(df3[df3$rho==-0.9, ], df30)
plot(df31$minprob, df31$mu, type = "b", 
     ylim = c(-3,1), xlim = rev(c(0.1,1)),
     xlab = "Probability of publishing study with smallest subjects",
     ylab = "Effect Size (lnOR)")
lines(df31$minprob, df31$mulb)
lines(df31$minprob, df31$muub)
abline(h=0)
title(main = "D. Proposal (HN, rho = -0.9)")

## rho = -0.6
df31 <- rbind(df3[df3$rho==-0.6, ], df30)
plot(df31$minprob, df31$mu, type = "b", 
     ylim = c(-3,1), xlim = rev(c(0.1,1)),
     xlab = "Probability of publishing study with smallest subjects",
     ylab = "Effect Size (lnOR)")
lines(df31$minprob, df31$mulb)
lines(df31$minprob, df31$muub)
abline(h=0)
title(main = "E. Proposal (HN, rho = -0.6)")

## rho = -0.3
df31 <- rbind(df3[df3$rho==-0.3, ], df30)
plot(df31$minprob, df31$mu, type = "b", 
     ylim = c(-3,1), xlim = rev(c(0.1,1)),
     xlab = "Probability of publishing study with smallest subjects",
     ylab = "Effect Size (lnOR)")
lines(df31$minprob, df31$mulb)
lines(df31$minprob, df31$muub)
abline(h=0)
title(main = "F. Proposal (HN, rho = -0.3)")


copdf <- data.frame(
  minprob = cop2a$publprob,
  mu = cop2a$TE.slope, 
  mulb = cop2a$lower.slope,
  muub = cop2a$upper.slope)
plot(copdf$minprob, copdf$mu, type = "b", 
     ylim = c(-3,1), xlim = rev(c(0.1,1)),
     xlab = "Probability of publishing study with largest SE",
     ylab = "Effect Size (lnOR)")
lines(copdf$minprob, copdf$mulb)
lines(copdf$minprob, copdf$muub)
abline(h=0)
title(main = "G. Copas selection model (rho = 0.9)")

copdf <- data.frame(
  minprob = cop2b$publprob,
  mu = cop2b$TE.slope, 
  mulb = cop2b$lower.slope,
  muub = cop2b$upper.slope)
plot(copdf$minprob, copdf$mu, type = "b", 
     ylim = c(-3,1), xlim = rev(c(0.1,1)),
     xlab = "Probability of publishing study with largest SE",
     ylab = "Effect Size (lnOR)")
lines(copdf$minprob, copdf$mulb)
lines(copdf$minprob, copdf$muub)
abline(h=0)
title(main = "H. Copas selection model (rho = 0.6)")

copdf <- data.frame(
  minprob = cop2c$publprob,
  mu = cop2c$TE.slope, 
  mulb = cop2c$lower.slope,
  muub = cop2c$upper.slope)
plot(copdf$minprob, copdf$mu, type = "b", 
     ylim = c(-3,1), xlim = rev(c(0.1,1)),
     xlab = "Probability of publishing study with largest SE",
     ylab = "Effect Size (lnOR)")
lines(copdf$minprob, copdf$mulb)
lines(copdf$minprob, copdf$muub)
abline(h=0)
title(main = "I. Copas selection model (rho = 0.3)")

par(mfrow = c(1,1))
```






